// Branchen-Daten für die öffentliche Website (Bilder: Unsplash, lizenzfrei)
export const BRANCHEN_INFO = [
  { id: 'handwerk', label: 'Handwerk & Bau', bild: 'photo-1504307651254-35680f356dfd',
    text: 'Leistungen sauber getrennt, Referenzen mit Bildern, Notdienst-Hinweis und Anfahrt.',
    bereiche: ['Leistungen mit Einzelbeschreibung', 'Referenzen & Galerie', 'Notdienst und Einsatzgebiet', 'Anfrageformular'] },
  { id: 'restaurant', label: 'Restaurant & Café', bild: 'photo-1517248135467-4c7edcad34c4',
    text: 'Speisekarte mit Kategorien und Preisen, Öffnungszeiten, Reservierungshinweis.',
    bereiche: ['Speisekarte nach Kategorien', 'Öffnungszeiten', 'Galerie vom Lokal', 'Reservierung & Anfahrt'] },
  { id: 'praxis', label: 'Arzt & Praxis', bild: 'photo-1576091160550-2173dba999ef',
    text: 'Behandlungen verständlich erklärt, Sprechzeiten, Team und Terminhinweis.',
    bereiche: ['Behandlungen & Leistungen', 'Sprechzeiten', 'Team mit Qualifikation', 'Terminvereinbarung'] },
  { id: 'anwalt', label: 'Anwalt & Kanzlei', bild: 'photo-1589829545856-d10d557cf95f',
    text: 'Rechtsgebiete, Werdegang, sachlicher Ton und Hinweis zur Erstberatung.',
    bereiche: ['Rechtsgebiete', 'Werdegang & Zulassung', 'Ablauf der Erstberatung', 'Kontakt & Vollmacht'] },
  { id: 'salon', label: 'Friseur & Beauty', bild: 'photo-1560066984-138dadb4c035',
    text: 'Leistungen mit Preisen, Galerie der Arbeiten, Team und Terminhinweis.',
    bereiche: ['Preisliste je Leistung', 'Galerie', 'Team', 'Termin & Öffnungszeiten'] },
  { id: 'fitness', label: 'Fitness & Sport', bild: 'photo-1534438327276-14e5300c3a48',
    text: 'Kursplan, Mitgliedschaften im Vergleich, Trainer und Probetraining.',
    bereiche: ['Kursplan', 'Mitgliedschaften im Vergleich', 'Trainer', 'Probetraining anfragen'] },
  { id: 'immobilien', label: 'Immobilien', bild: 'photo-1560518883-ce09059eeffa',
    text: 'Objekte, Leistungen für Verkäufer, Bewertung anfragen, Ablauf erklärt.',
    bereiche: ['Objekte & Referenzen', 'Leistungen für Verkäufer', 'Ablauf einer Vermittlung', 'Bewertung anfragen'] },
  { id: 'agentur', label: 'Agentur & Beratung', bild: 'photo-1497366754035-f200968a6e72',
    text: 'Leistungen, Arbeitsweise, Referenzen und Weg zum Erstgespräch.',
    bereiche: ['Leistungen', 'Arbeitsweise in Schritten', 'Referenzen', 'Erstgespräch buchen'] },
  { id: 'fahrschule', label: 'Fahrschule & Bildung', bild: 'photo-1449965408869-eaa3f722e40d',
    text: 'Führerscheinklassen, Preise transparent, Unterrichtszeiten und Anmeldung.',
    bereiche: ['Klassen & Voraussetzungen', 'Preise transparent', 'Unterrichtszeiten', 'Anmeldung'] },
  { id: 'andere', label: 'Andere Branche', bild: 'photo-1497366216548-37526070297c',
    text: 'Auch alles andere: Die Inhalte richten sich nach deinen Angaben im Wizard.',
    bereiche: ['Leistungen frei benennbar', 'Über uns', 'Galerie', 'Kontakt'] },
]

export const BILD = (id, w = 900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=75`
