// Zentrale FAQ – wird auf Startseite (Auszug) und Hilfe-Seite (vollständig) genutzt
export const FRAGEN = [
  { g: 'Preise & Abrechnung', f: 'Was kostet eine Website hier genau?', a: 'Kaufen: einmalig 89 € inkl. MwSt. (Onepager), 149 € inkl. MwSt. (Multipage) oder 199 € inkl. MwSt. (Business). Kein Abo. Mieten: monatlich 19,90 € inkl. MwSt. (Start), 29,90 € inkl. MwSt. (Plus) oder 39,90 € inkl. MwSt. (Pro) — jeweils inklusive Domain, Hosting und SSL, bei zwölf Monaten Mindestlaufzeit und einmalig 49 € inkl. MwSt. Einrichtung.', top: true },
  { g: 'Preise & Abrechnung', f: 'Was ist der Unterschied zwischen kaufen und mieten?', a: 'Beim Kauf bekommst du alle Dateien als ZIP und betreibst die Website, wo du willst — Hosting und Domain besorgst du selbst. Bei der Miete läuft alles bei uns: Domain, Server, SSL, Sicherungen und E-Mail. In beiden Fällen kannst du die Website dauerhaft selbst im Editor ändern.', top: true },
  { g: 'Preise & Abrechnung', f: 'Wie lange läuft der Mietvertrag?', a: 'Zwölf Monate Mindestlaufzeit, danach monatlich kündbar mit einem Monat Frist. Der Grund für die zwölf Monate ist die Domain, die jahresweise bezahlt wird. Kündigen kannst du im Kontobereich oder per E-Mail — ohne Begründung.', top: true },
  { g: 'Preise & Abrechnung', f: 'Wie wird abgerechnet, wenn ich mitten im Monat starte?', a: 'Dein Abrechnungszeitraum beginnt am Tag der Bestellung. Startest du am 25., läuft dein Monat immer vom 25. bis zum 24. — es gibt also keine Teilmonate und keine anteilige Berechnung. Die Rechnung kommt automatisch per E-Mail und liegt in deinem Kontobereich.' },
  { g: 'Preise & Abrechnung', f: 'Fallen Kosten für Änderungen an?', a: 'Nein. Änderungen machst du selbst im Editor, so oft du willst — kostenlos. Das gilt beim Kauf wie bei der Miete. Nur wenn wir Änderungen für dich übernehmen sollen, wird das gesondert vereinbart.', top: true },
  { g: 'Preise & Abrechnung', f: 'Bekomme ich eine ordentliche Rechnung?', a: 'Ja, automatisch als PDF mit Rechnungsnummer, ausgewiesener Umsatzsteuer und deinen Firmendaten. Bei Bestellung auf ein Unternehmen mit USt-IdNr. wird diese auf der Rechnung ausgewiesen. Hinterleg deine Daten vorher unter „Meine Daten".' },

  { g: 'Ablauf', f: 'Wie lange dauert es wirklich?', a: 'Die Angaben im Wizard brauchen etwa zehn Minuten, die Erstellung ein bis zwei Minuten. Für die Feinarbeit im Editor plan eine halbe Stunde ein: Texte prüfen, eigene Bilder einsetzen, Farben anpassen.', top: true },
  { g: 'Ablauf', f: 'Brauche ich Vorkenntnisse?', a: 'Nein. Du beantwortest Fragen zu deinem Betrieb — Branche, Leistungen, Öffnungszeiten, Kontakt. Im Editor änderst du Texte durch Anklicken, wie in einem Textprogramm.', top: true },
  { g: 'Ablauf', f: 'Muss ich mich registrieren?', a: 'Zum Ausprobieren nicht. Du kannst den ganzen Wizard durchgehen und alles ansehen. Ein Konto brauchst du erst, wenn die Website erzeugt wird — damit du sie wiederfindest und wir Missbrauch verhindern.' },
  { g: 'Ablauf', f: 'Und wenn mir das Ergebnis nicht gefällt?', a: 'Du siehst die fertige Website, bevor du zahlst. Du kannst Layout, Farben und Texte beliebig ändern oder den Wizard neu durchlaufen.' },

  { g: 'Inhalte & Bilder', f: 'Kann ich eigene Bilder verwenden?', a: 'Ja, bis zu 20 Stück als WebP, JPG oder PNG. Du kannst jedes Bild beschreiben, damit es an der richtigen Stelle landet. Du brauchst die Nutzungsrechte an den Bildern — das bestätigst du beim Hochladen.', top: true },
  { g: 'Inhalte & Bilder', f: 'Woher kommen die KI-Bilder?', a: 'Sie werden für dich erzeugt, nicht aus einer Datenbank kopiert. Je Paket sind 6 bis 12 Bilder enthalten; weitere kosten 1,50 € inkl. MwSt. pro Bild. Prüfe die Bilder trotzdem: KI-Bilder eignen sich gut für Stimmung, nicht für konkrete Produkte oder Personen.' },
  { g: 'Inhalte & Bilder', f: 'Sind die Texte einzigartig?', a: 'Sie werden für deinen Betrieb aus deinen Angaben geschrieben, nicht aus Vorlagen kopiert. Lies sie durch und schärfe nach, wo es auf Details ankommt — bei Preisen, Leistungen und Fachbegriffen.' },
  { g: 'Inhalte & Bilder', f: 'Was ist mit Kundenstimmen?', a: 'Der Generator legt Platzhalter an. Ersetze sie durch echte Bewertungen. Erfundene Kundenstimmen sind Wettbewerbsverstöße und können abgemahnt werden — lass sie besser weg, wenn du keine echten hast.' },

  { g: 'Technik & Domain', f: 'Wird die Website bei Google gefunden?', a: 'Die technischen Grundlagen sind vorhanden: saubere Überschriften, schnelle Ladezeit, für Handy optimiert, Titel und Beschreibung aus deinen SEO-Angaben. Eine Garantie für Platzierungen gibt es nicht — die hängt von Wettbewerb, Ort und Inhalten ab.' },
  { g: 'Technik & Domain', f: 'Wem gehört die Domain?', a: 'Dir. Die Domain wird auf deinen Namen registriert, du bist Inhaber. Wir übernehmen die technische Verwaltung. Wechselst du den Anbieter, nimmst du sie mit.', top: true },
  { g: 'Technik & Domain', f: 'Kann ich eine bestehende Domain nutzen?', a: 'Ja. Beim Kauf lädst du die Dateien einfach zu deinem Anbieter hoch. Bei der Miete kannst du deine Domain zu uns umziehen oder per DNS auf unseren Server zeigen lassen.' },
  { g: 'Technik & Domain', f: 'Bekomme ich eine E-Mail-Adresse?', a: 'Bei der Miete: im Paket Start eine Weiterleitung auf deine bestehende Adresse, ab Plus ein echtes Postfach mit Webmail und Spam-Filter. Weitere Postfächer kosten 3 € inkl. MwSt. im Monat.' },
  { g: 'Technik & Domain', f: 'Wem gehört die Website?', a: 'Dir. Beim Kauf bekommst du den kompletten Quellcode als ZIP — HTML und CSS, ohne Bindung. Auch bei der Miete kannst du die Dateien jederzeit herunterladen.', top: true },

  { g: 'Recht & Daten', f: 'Was ist mit Impressum und Datenschutz?', a: 'Für die Inhalte deiner Website bist du verantwortlich, auch für Impressum und Datenschutzerklärung. Wir erzeugen dir aus deinen Angaben Vorlagen. Das ist keine Rechtsberatung — bei besonderen Anforderungen, etwa Praxen, Kanzleien oder Onlineverkauf, lass sie prüfen.', top: true },
  { g: 'Recht & Daten', f: 'Wo liegen meine Daten?', a: 'Konto- und Projektdaten liegen in einer Datenbank in Frankfurt am Main. Für die Erzeugung von Texten und Bildern werden deine Wizard-Angaben an Dienstleister in den USA übermittelt — auf Grundlage von Standardvertragsklauseln. Details stehen in der Datenschutzerklärung.' },
  { g: 'Recht & Daten', f: 'Setzt die Seite Cookies?', a: 'Nur technisch notwendige: einen Anmelde-Token, damit du eingeloggt bleibst, und den Browser-Zwischenspeicher für deinen Entwurf. Keine Werbe- oder Analyse-Cookies, kein Tracking. Deshalb gibt es hier auch kein Cookie-Banner.' },
  { g: 'Recht & Daten', f: 'Kann ich mein Konto löschen?', a: 'Ja, jederzeit unter „Meine Daten". Mit dem Konto werden auch deine Projekte gelöscht. Rechnungsdaten müssen wir gesetzlich zehn Jahre aufbewahren.' },
]

export const GRUPPEN_REIHE = ['Preise & Abrechnung', 'Ablauf', 'Inhalte & Bilder', 'Technik & Domain', 'Recht & Daten']
